### ISSUE TITLE
Task: Release checklist

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/jacoco-cov-badge-maven-plugin#24]
- [x] Change release versions in wiki and in `pom.xml`
- [x] Rename groupid to `io.githug.handofgod94`
- [x] Create javadocs jar
- [x] File signing GPG
- [x] Add description and url pointing to wiki in `pom.xml`
- [x] Add dev info and profile link in `pom.xml`
- [x] SCM information to `pom.xml`
- [x] Verify all the TODOs in code
- [x] Update README and Wiki with new groupId
- [x] Seperate build profile for `release`

**Comment by HandOfGod94** [comment]
Waiting for approval from ORSSH, once its done will release v1.0.0
