### ISSUE TITLE
Task: Post Release Checklist

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/jacoco-cov-badge-maven-plugin#27]
- [x] Verify it available in `maven` central
- [x] Verify if we are able to download it successfully or not.
- [x] Update README for both the branches... i.e. `release-1.0.0` an `master`.
  * Add quickstart
  * Update features (i.e. coverage category)
- [x] Update wiki with correct artifact and group id and with new quick start guide.
  * Update features (i.e. coverage category)
- [x] Document release branch and patches convention in `Contributing` guidelines.
- [x] Add `CHANGELOG`

**Comment by HandOfGod94** [comment]
Need to do same things for v1.1.0

**Comment by HandOfGod94** [comment]
## For release 1.1.0
- [x] Verify it available in `maven` central
- [x] Verify if we are able to download it successfully or not.
- [x] Update README for both the branches... i.e. `release-1.0.0` an `master`.
  * Add quickstart
  * Update features (i.e. coverage category)
- [x] Update wiki with correct artifact and group id and with new quick start guide.
  * Update features (i.e. coverage category)
- [x] Add `CHANGELOG`
