### ISSUE TITLE
Task: Create a deployment pipeline using Travis

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/jacoco-cov-badge-maven-plugin#43]
## Purpose
Currently `travis` builds are uniform irrespective of it's PR, a single branch commit, master commit or release. The vision is to have separate builds for `pr`, for `branch` and `release`

## Tasks
- [x] modify `travis` config for branch commits
  - should run tests and checkstyle
- [x] modify `travis` config for PR
  - it should only run tests and checkstyle
  - check coverage and fail if below certain (Set to 80%)
- [x] modify `travis` config for release
  * [x] should run tests and checkstyle
  * [x] check coverage and fail if below certain threshold (~use codeacy~, used coveralls)
  * [x] a separate travis stage to push it to `sonatype` repo

> ~Need to use `travis` stages feature to separate out staged builds.~ DONE
> **Coverage Threshold is now at 80% and decrease %age threshold is at 5%**
